#!/bin/sh -eu

. settings.sh

######################################################################

mkdir -p -- "$fig_dir"

#for f in $vmap_dir/*.vmap; do
for base in $(cat list.txt); do
  v="$vmap_dir/$base.vmap"
  f="$fig_dir/$base.fig"
  l="$lab_dir/$base.vmap"

  if [ "$v" -nt "$f" ]; then
    echo "updating $base"
    vmap_1km_filter 1 "$v" "$base.vmap"
    label_src=
    border=
    if [ -f "$l" ]; then
      label_src="$l"
    elif [ -f "$f" ]; then
      label_src="$f"
      border="--keep_border"
    else
      label_src="$base.vmap"
      border="--set_brd_from_range"
    fi
    vmap_copy -v --skip_labels "$base.vmap"\
            $label_src --read_labels --skip_all --split_labels\
            -o "$f"\
            --rscale $rscale --name $base --range_nom=$base

    rm -f -- "$base.vmap"
  fi

done
